name: Size Guard

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  size-guard:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper diff
    
    - name: Check Git LFS compliance
      run: |
        echo "Checking Git LFS compliance..."
        
        # Install Git LFS
        git lfs install
        
        # Run LFS verification script
        if [ -f "scripts/verify_lfs.sh" ]; then
          chmod +x scripts/verify_lfs.sh
          ./scripts/verify_lfs.sh
        else
          echo "❌ ERROR: scripts/verify_lfs.sh not found"
          exit 1
        fi
    
    - name: Verify LFS is active
      run: |
        echo "Verifying Git LFS is active..."
        git lfs ls-files
        lfs_count=$(git lfs ls-files | wc -l)
        echo "LFS tracked files: $lfs_count"
        
        if [ $lfs_count -gt 0 ]; then
          echo "✅ Git LFS is active with $lfs_count tracked files"
        else
          echo "ℹ️  No files currently tracked by LFS (this may be normal)"
        fi
    
    - name: Check repository size
      run: |
        echo "Checking total repository size..."
        REPO_SIZE=$(du -sh . | cut -f1)
        echo "Repository size: $REPO_SIZE"
        
        # Warn if repository is getting large
        REPO_SIZE_MB=$(du -sm . | cut -f1)
        if [ $REPO_SIZE_MB -gt 1000 ]; then
          echo "⚠️  WARNING: Repository size is ${REPO_SIZE_MB}MB"
          echo "Consider using git LFS or external storage for large files"
        fi
